easy_admin:
    site_name: 'Админ-панель'
    design:
        assets:
            css:
                - 'css/admin.css'
    list:
        max_results: 100
    show:
        max_results: 100
    entities:
        Product:
            class: App\Entity\Product
            label: "Товар"
            list:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Название'}
                    - { property: 'path', label: 'Ссылка', type: 'url'}
                    - { property: 'price', label: 'Цена'}
                    - { property: 'imageSmall', label: 'Изображение', type: 'image'}
                   # - {property: 'discount', label: 'Скидка'}
                    - { property: 'type.name', label: 'Тип'}
                    - { property: 'material.name', label: 'Подтип'}
                    - { property: 'color.name', label: 'Цвет'}
                    - { property: 'category.name', label: 'Категория'}
                    - { property: 'popular', label: 'Популярный'}
                    - { property: 'published', label: 'Опубликован'}
                filters:
                    - { property: 'name', label: 'Название'}
                    - { property: 'uri', label: 'Ссылка'}
                    - { property: 'price', label: 'Цена'}
                    - { property: 'type', label: 'Тип'}
                    - { property: 'material', label: 'Подтип'}
                    - { property: 'color', label: 'Цвет'}
                    - { property: 'category', label: 'Категория'}
                    - { property: 'popular', label: 'Популярный'}
                    - { property: 'published', label: 'Опубликован'}
                sort: ['id', 'ASC']

        Catalog:
            class: App\Entity\Catalog
            label: "Каталог"
            list:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Название'}
                    - { property: 'path', label: 'Ссылка', type: 'url'}
                    - { property: 'parent', label: 'Родитель'}
                    - { property: 'published', label: 'Опубликован'}
                    - { property: 'type.name', label: 'Тип'}
                    - { property: 'material.name', label: 'Подтип'}
                sort: ['id', 'ASC']

        Simple:
            class: App\Entity\Simple
            label: "Простая страница"
            list:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Название'}
                    - { property: 'path', label: 'Ссылка', type: 'url'}
                    - { property: 'published', label: 'Опубликован'}
                sort: ['id', 'ASC']
        Type:
            class: App\Entity\Type
            label: "Тип"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
                    - {property: 'materials', label: 'Кол-во материалов'}
                    - {property: 'catalogs', label: 'Кол-во каталогов'}
                    - {property: 'showMainPageCalc', label: 'Калькулятор на главной', type: 'toggle'}
            form:
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'materials', label: 'Подтипы', type_options: { by_reference: false }}
                    - {property: 'showMainPageCalc', label: 'Калькулятор на главной', type: 'checkbox'}
                    - {property: 'calculationType', label: 'Тип рассчета',type: 'text'}
                    - {property: 'products', label: 'Товары', type: easyadmin_autocomplete }
        Color:
            class: App\Entity\Color
            label: "Цвет"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'alias', label: 'Алиас'}
                    - {property: 'hex', label: 'Hex-код'}
                    - {property: 'products', label: 'Кол-во товаров'}
        Material:
            class: App\Entity\Material
            label: "Подтип"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
                    - {property: 'catalogs', label: 'Кол-во каталогов'}
            form:
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'type', label: 'Тип'}
                    - {property: 'products', label: 'Товары', type: easyadmin_autocomplete }
        Category:
            class: App\Entity\Category
            label: "Категория"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
        Config:
            class: App\Entity\Config
            label: "Настройки"
            list:
                fields:
                    - {property: 'title', label: 'Название параметра'}
                    - {property: 'name', label: 'Системное имя'}
                    - {property: 'value', label: 'Значение параметра'}
            form:
                fields:
                    - {property: 'title', label: 'Название параметра'}
                    - {property: 'name', label: 'Системное имя'}
                    - {property: 'value', label: 'Значение параметра'}
