easy_admin:
    site_name: 'Админ-панель'
    design:
        assets:
            css:
                - 'css/admin.css'
    list:
        max_results: 50
    show:
        max_results: 50
    entities:
        Product:
            class: App\Entity\Product
            label: "Товар"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'uri', label: 'Ссылка'}
                    - {property: 'price', label: 'Цена'}
                    - {property: 'type.name', label: 'Тип'}
                    - {property: 'material.name', label: 'Материал'}
                    - {property: 'color.name', label: 'Цвет'}
                    - {property: 'published', label: 'Опубликован'}
        Catalog:
            class: App\Entity\Catalog
            label: "Каталог"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'uri', label: 'Ссылка'}
                    - {property: 'published', label: 'Опубликован'}
        Type:
            class: App\Entity\Type
            label: "Тип"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
        Color:
            class: App\Entity\Color
            label: "Цвет"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
        Material:
            class: App\Entity\Material
            label: "Материал"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
