easy_admin:
    site_name: 'Админ-панель'
    design:
        assets:
            css:
                - 'css/admin.css'
    list:
        max_results: 100
    show:
        max_results: 100
    entities:
        Product:
            class: App\Entity\Product
            label: "Товар"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'path', label: 'Ссылка', type: 'url'}
                    - {property: 'price', label: 'Цена'}
                    - {property: 'type.name', label: 'Тип'}
                    - {property: 'material.name', label: 'Материал'}
                    - {property: 'color.name', label: 'Цвет'}
                    - {property: 'category.name', label: 'Категория'}
                    - {property: 'popular', label: 'Популярный'}
                    - {property: 'published', label: 'Опубликован'}
                filters:
                    - {property: 'name', label: 'Название'}
                    - {property: 'uri', label: 'Ссылка'}
                    - {property: 'price', label: 'Цена'}
                    - {property: 'type', label: 'Тип'}
                    - {property: 'material', label: 'Материал'}
                    - {property: 'color', label: 'Цвет'}
                    - {property: 'category', label: 'Категория'}
                    - {property: 'popular', label: 'Популярный'}
                    - {property: 'published', label: 'Опубликован'}
        Catalog:
            class: App\Entity\Catalog
            label: "Каталог"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'path', label: 'Ссылка', type: 'url'}
                    - {property: 'published', label: 'Опубликован'}
        Type:
            class: App\Entity\Type
            label: "Тип"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
                    - {property: 'materials', label: 'Кол-во материалов'}
            form:
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'materials', label: 'Материалы'}
        Color:
            class: App\Entity\Color
            label: "Цвет"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
        Material:
            class: App\Entity\Material
            label: "Материал"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
            form:
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'type', label: 'Тип'}
        Category:
            class: App\Entity\Category
            label: "Категория"
            list:
                fields:
                    - 'id'
                    - {property: 'name', label: 'Название'}
                    - {property: 'products', label: 'Кол-во товаров'}
