# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path: "build/ckeditor/ckeditor.js"
    configs:
        simple_config:
            allowedContent: true
            autoParagraph: false
            extraPlugins: [ 'image2','div', 'uploadimage', 'justify' ]
            imageUploadUrl: '/admin/upload-images/cke'
