vich_uploader:
    db_driver: orm

    mappings:
        seo_images:
            uri_prefix:         ''
            upload_destination: '%kernel.project_dir%/%web_root%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'seoImgFolder' }
        card_images:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/%web_root%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'cardImgFolder' }
        product_images_small:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/%web_root%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'productImgSmallFolder' }
        product_images_big:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/%web_root%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'productImgBigFolder' }
        product_images_catalog:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/%web_root%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'productImgCatalogFolder' }
