vich_uploader:
    db_driver: orm

    mappings:
        web_root:
            uri_prefix:         ''
            upload_destination: '%kernel.project_dir%/%web_root%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'imgFolder'}
        location_images:
            uri_prefix:         '%app.path.location_images%'
            upload_destination: '%kernel.project_dir%/%web_root%%app.path.location_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
