vich_uploader:
    db_driver: orm

    mappings:
        seo_images:
            uri_prefix:         '%app.path.seo_images%'
            upload_destination: '%kernel.project_dir%/%web_root%%app.path.seo_images%'
